[package]
name = "ruce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-llvm-cov = "0.5.25"
thiserror = "1.0.44"

